#!/usr/bin/env bash
set -euo pipefail

group_name="benchgroup"
name_prefix="bench_"

usage() {
    cat <<USAGE
Usage:
  ./scripts/cleanup_bench_sql.sh [options]

Options:
  --group-name NAME    Group name to delete (default: benchgroup)
  --name-prefix PREFIX Username prefix to delete (default: bench_)
  -h, --help           Show this help

Example:
  ./scripts/cleanup_bench_sql.sh > /tmp/bench_cleanup.sql
USAGE
}

sql_escape() {
    local s="$1"
    s="${s//\'/\'\'}"
    printf "%s" "$s"
}

sql_like_escape() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//%/\\%}"
    s="${s//_/\\_}"
    printf "%s" "$s"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --group-name)
            group_name="${2:-}"
            shift 2
            ;;
        --name-prefix)
            name_prefix="${2:-}"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Error: unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

if [[ -z "$name_prefix" ]]; then
    echo "Error: name_prefix cannot be empty." >&2
    exit 1
fi

group_name_escaped="$(sql_escape "$group_name")"
name_prefix_like="$(sql_like_escape "$name_prefix")"

cat <<EOF2
-- Cleanup SQL generated by scripts/cleanup_bench_sql.sh
START TRANSACTION;

CREATE TEMPORARY TABLE tmp_bench_users (id INT PRIMARY KEY);
INSERT INTO tmp_bench_users(id)
SELECT id FROM user
WHERE name LIKE '${name_prefix_like}%' ESCAPE '\\';

CREATE TEMPORARY TABLE tmp_bench_groups (id INT PRIMARY KEY);
INSERT INTO tmp_bench_groups(id)
SELECT id FROM allgroup
WHERE groupname = '${group_name_escaped}';

-- Delete dependent rows first to support databases without foreign keys.
DELETE FROM groupuser
WHERE userid IN (SELECT id FROM tmp_bench_users)
   OR groupid IN (SELECT id FROM tmp_bench_groups);

DELETE FROM friend
WHERE userid IN (SELECT id FROM tmp_bench_users)
   OR friendid IN (SELECT id FROM tmp_bench_users);

DELETE FROM offlinemessage
WHERE userid IN (SELECT id FROM tmp_bench_users);

DELETE FROM allgroup
WHERE id IN (SELECT id FROM tmp_bench_groups);

DELETE FROM user
WHERE id IN (SELECT id FROM tmp_bench_users);

DROP TEMPORARY TABLE IF EXISTS tmp_bench_groups;
DROP TEMPORARY TABLE IF EXISTS tmp_bench_users;

COMMIT;
EOF2
