#!/usr/bin/env bash
set -euo pipefail

start_user_id=""
user_count="200"
group_member_count="21"
group_name="benchgroup"
group_desc="benchmark"
name_prefix="bench_"
password="bench123"
state="offline"

usage() {
    cat <<USAGE
Usage:
  ./scripts/generate_bench_sql.sh [options]

Options:
  --start-user-id N       Optional fixed start user id. If omitted, use AUTO_INCREMENT ids.
  --user-count N          Number of users to create (default: 200)
  --group-member-count N  Number of users to join the group (default: 21)
  --group-name NAME       Group name (default: benchgroup)
  --group-desc DESC       Group description (default: benchmark)
  --name-prefix PREFIX    Username prefix (default: bench_)
  --password PASS         User password (default: bench123)
  --state STATE           User state (default: offline)
  -h, --help              Show this help

Example:
  ./scripts/generate_bench_sql.sh --user-count 200 --group-member-count 21 > /tmp/bench_seed.sql
  ./scripts/generate_bench_sql.sh --start-user-id 10001 > /tmp/bench_seed_fixed_id.sql
USAGE
}

is_positive_int() {
    [[ "$1" =~ ^[1-9][0-9]*$ ]]
}

sql_escape() {
    local s="$1"
    s="${s//\'/\'\'}"
    printf "%s" "$s"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --start-user-id)
            start_user_id="${2:-}"
            shift 2
            ;;
        --user-count)
            user_count="${2:-}"
            shift 2
            ;;
        --group-member-count)
            group_member_count="${2:-}"
            shift 2
            ;;
        --group-name)
            group_name="${2:-}"
            shift 2
            ;;
        --group-desc)
            group_desc="${2:-}"
            shift 2
            ;;
        --name-prefix)
            name_prefix="${2:-}"
            shift 2
            ;;
        --password)
            password="${2:-}"
            shift 2
            ;;
        --state)
            state="${2:-}"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Error: unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

if [[ -n "$start_user_id" ]] && ! is_positive_int "$start_user_id"; then
    echo "Error: start_user_id must be a positive integer." >&2
    exit 1
fi

if ! is_positive_int "$user_count"; then
    echo "Error: user_count must be a positive integer." >&2
    exit 1
fi

if ! is_positive_int "$group_member_count"; then
    echo "Error: group_member_count must be a positive integer." >&2
    exit 1
fi

if (( group_member_count > user_count )); then
    echo "Error: group_member_count cannot be greater than user_count." >&2
    exit 1
fi

if [[ -z "$name_prefix" ]]; then
    echo "Error: name_prefix cannot be empty." >&2
    exit 1
fi

width="${#user_count}"
if (( width < 3 )); then
    width=3
fi

group_name_escaped="$(sql_escape "$group_name")"
group_desc_escaped="$(sql_escape "$group_desc")"
name_prefix_escaped="$(sql_escape "$name_prefix")"
password_escaped="$(sql_escape "$password")"
state_escaped="$(sql_escape "$state")"

cat <<EOF2
-- Benchmark seed SQL generated by scripts/generate_bench_sql.sh
-- user_count=${user_count}, group_member_count=${group_member_count}, mode=$([[ -n "$start_user_id" ]] && echo "fixed_user_id" || echo "auto_increment")
START TRANSACTION;

EOF2

if [[ -n "$start_user_id" ]]; then
    echo "INSERT INTO user(id, name, password, state) VALUES"
    for ((i = 1; i <= user_count; i++)); do
        user_id=$((start_user_id + i - 1))
        username="$(printf "%s%0${width}d" "$name_prefix_escaped" "$i")"
        if (( i == user_count )); then
            printf "(%d, '%s', '%s', '%s');\n" "$user_id" "$username" "$password_escaped" "$state_escaped"
        else
            printf "(%d, '%s', '%s', '%s'),\n" "$user_id" "$username" "$password_escaped" "$state_escaped"
        fi
    done
else
    echo "INSERT INTO user(name, password, state) VALUES"
    for ((i = 1; i <= user_count; i++)); do
        username="$(printf "%s%0${width}d" "$name_prefix_escaped" "$i")"
        if (( i == user_count )); then
            printf "('%s', '%s', '%s');\n" "$username" "$password_escaped" "$state_escaped"
        else
            printf "('%s', '%s', '%s'),\n" "$username" "$password_escaped" "$state_escaped"
        fi
    done

    echo "SET @bench_first_user_id = LAST_INSERT_ID();"
fi

cat <<EOF2

INSERT INTO allgroup(groupname, groupdesc) VALUES ('${group_name_escaped}', '${group_desc_escaped}');
SET @bench_group_id = LAST_INSERT_ID();

INSERT INTO groupuser(groupid, userid, grouprole) VALUES
EOF2

for ((i = 0; i < group_member_count; i++)); do
    if [[ -n "$start_user_id" ]]; then
        user_ref="$((start_user_id + i))"
    else
        user_ref="(@bench_first_user_id + ${i})"
    fi

    if (( i + 1 == group_member_count )); then
        printf "(@bench_group_id, %s, 'normal');\n" "$user_ref"
    else
        printf "(@bench_group_id, %s, 'normal'),\n" "$user_ref"
    fi
done

echo
echo "COMMIT;"
